### PR TITLE
Change bold titles to h4

### PR DESCRIPTION
**Pull request by ShadowJonathan**
This makes it in-line with other templates, and also looks nicer

### CODE REVIEW

**Comment by Greraf** [comment]
This makes it in-line with other templates, and also looks nicer

**Comment by Greraf** [comment]
README file

**Comment by Greraf** [comment]
77d25c

**Comment by turt2live** [comment]
Thank you for the contribution, however the templates in this repo are consistent with each other already. It is intended that projects which are using these templates actually override them if needed.

**Pull request closed without merging**
